spring:
  application:
    name: ai-counseling-app
  profiles:
    active: dev  # 기본 프로파일

  jpa:
    open-in-view: false  # 성능 최적화

  security:
    user:
      name: admin
      password: admin  # 개발용 임시

# Actuator 설정 (헬스체크)
management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# 로깅 설정
logging:
  level:
    root: INFO
    com.aicounseling: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# OAuth2 설정
oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID:861362260494-2gn00elrv3doj3hm8il79qkghf0jvo4g.apps.googleusercontent.com}
    # Android 앱은 client-secret 필요 없음
  kakao:
    client-id: ${KAKAO_CLIENT_ID:}
  naver:
    client-id: ${NAVER_CLIENT_ID:}
    client-secret: ${NAVER_CLIENT_SECRET:}

# JWT 설정
jwt:
  secret: ${JWT_SECRET:this-is-a-very-long-secret-key-for-jwt-authentication-that-is-at-least-256-bits-long-for-security-requirements-2025}
  expiration: 86400000  # 24시간 (밀리초)
  refresh-expiration: 604800000  # 7일

# OpenRouter API 설정
openrouter:
  api-key: ${OPENROUTER_API_KEY}
  base-url: https://openrouter.ai/api/v1
  model: google/gemini-2.5-flash-lite
  site-url: http://localhost:8080
  site-name: AI Counseling App
  timeout: 60

# SpringDoc OpenAPI 설정
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    filter: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# 서버 설정
server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never
