spring:
  application:
    name: ai-counseling-app
  profiles:
    active: dev  # 기본 프로파일
    
  jpa:
    open-in-view: false  # 성능 최적화
    
  security:
    user:
      name: admin
      password: admin  # 개발용 임시

# Actuator 설정 (헬스체크)
management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      
# 로깅 설정
logging:
  level:
    root: INFO
    com.aicounseling: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    
# JWT 설정
jwt:
  secret: ${JWT_SECRET:this-is-a-very-long-secret-key-for-jwt-authentication-that-is-at-least-256-bits-long-for-security-requirements-2024}
  expiration: 86400000  # 24시간 (밀리초)
  refresh-expiration: 604800000  # 7일

# OpenRouter API 설정
openrouter:
  api-key: ${OPENROUTER_API_KEY}
  base-url: https://openrouter.ai/api/v1
  model: openai/gpt-4o-mini
  timeout: 60

# 서버 설정
server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never